apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wazuh-storage
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_LRS
  storageaccounttype: Standard_LRS
  kind: managed
reclaimPolicy: Retain
volumeBindingMode: Immediate